(cl:defpackage hexapodservice-msg
  (:use )
  (:export
   "<LEGJOINTS>"
   "LEGJOINTS"
   "<LEGS>"
   "LEGS"
   "<HEXAPODSERVICEACTION>"
   "HEXAPODSERVICEACTION"
   "<HEXAPODSERVICEACTIONRESULT>"
   "HEXAPODSERVICEACTIONRESULT"
   "<HEXAPODSERVICEGOAL>"
   "HEXAPODSERVICEGOAL"
   "<HEXAPODSERVICEFEEDBACK>"
   "HEXAPODSERVICEFEEDBACK"
   "<HEXAPODSERVICEACTIONFEEDBACK>"
   "HEXAPODSERVICEACTIONFEEDBACK"
   "<HEXAPODSERVICEACTIONGOAL>"
   "HEXAPODSERVICEACTIONGOAL"
   "<HEXAPODSERVICERESULT>"
   "HEXAPODSERVICERESULT"
  ))

