#ifndef DEFINE_H_
#define DEFINE_H_

#define SIMPLEMOTION_CONTROL 0
#define ONELEG_CONTROL 1
#define ALLLEGS_CONTROL 2
#define ONELEG_RESET 3
#define ALLLEGS_RESET 4

#define OPENBUS 1
#define CLOSEBUS 2
#define ENABLEMOTOR 3
#define DISABLEMOTOR 4
#define GETSTATUS 5
#define CLEARFAULT 6
#define ONELEGRESET 7
#define ALLLEGRESET 8


#endif