// Generated by gencpp from file hexapodservice/hexapodserviceGoal.msg
// DO NOT EDIT!


#ifndef HEXAPODSERVICE_MESSAGE_HEXAPODSERVICEGOAL_H
#define HEXAPODSERVICE_MESSAGE_HEXAPODSERVICEGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <hexapodservice/legjoints.h>
#include <hexapodservice/legs.h>

namespace hexapodservice
{
template <class ContainerAllocator>
struct hexapodserviceGoal_
{
  typedef hexapodserviceGoal_<ContainerAllocator> Type;

  hexapodserviceGoal_()
    : MODE(0)
    , SIMPLEMOTION_MODE(0)
    , ONELEG()
    , ALLLEGS()  {
    }
  hexapodserviceGoal_(const ContainerAllocator& _alloc)
    : MODE(0)
    , SIMPLEMOTION_MODE(0)
    , ONELEG(_alloc)
    , ALLLEGS(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _MODE_type;
  _MODE_type MODE;

   typedef int32_t _SIMPLEMOTION_MODE_type;
  _SIMPLEMOTION_MODE_type SIMPLEMOTION_MODE;

   typedef  ::hexapodservice::legjoints_<ContainerAllocator>  _ONELEG_type;
  _ONELEG_type ONELEG;

   typedef  ::hexapodservice::legs_<ContainerAllocator>  _ALLLEGS_type;
  _ALLLEGS_type ALLLEGS;




  typedef boost::shared_ptr< ::hexapodservice::hexapodserviceGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hexapodservice::hexapodserviceGoal_<ContainerAllocator> const> ConstPtr;

}; // struct hexapodserviceGoal_

typedef ::hexapodservice::hexapodserviceGoal_<std::allocator<void> > hexapodserviceGoal;

typedef boost::shared_ptr< ::hexapodservice::hexapodserviceGoal > hexapodserviceGoalPtr;
typedef boost::shared_ptr< ::hexapodservice::hexapodserviceGoal const> hexapodserviceGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hexapodservice::hexapodserviceGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hexapodservice::hexapodserviceGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hexapodservice

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'hexapodservice': ['/home/quan/hexapod_service_ws/src/hexapodservice/msg', '/home/quan/hexapod_service_ws/src/hexapodservice/devel/share/hexapodservice/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hexapodservice::hexapodserviceGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hexapodservice::hexapodserviceGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hexapodservice::hexapodserviceGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hexapodservice::hexapodserviceGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hexapodservice::hexapodserviceGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hexapodservice::hexapodserviceGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hexapodservice::hexapodserviceGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f06e836a6f264cb71055ead4d7dfa381";
  }

  static const char* value(const ::hexapodservice::hexapodserviceGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf06e836a6f264cb7ULL;
  static const uint64_t static_value2 = 0x1055ead4d7dfa381ULL;
};

template<class ContainerAllocator>
struct DataType< ::hexapodservice::hexapodserviceGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hexapodservice/hexapodserviceGoal";
  }

  static const char* value(const ::hexapodservice::hexapodserviceGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hexapodservice::hexapodserviceGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
int32 MODE \n\
int32 SIMPLEMOTION_MODE\n\
hexapodservice/legjoints ONELEG\n\
hexapodservice/legs ALLLEGS\n\
\n\
================================================================================\n\
MSG: hexapodservice/legjoints\n\
float64 coxa\n\
float64 femur\n\
float64 tibia\n\
float64 tarsus\n\
\n\
================================================================================\n\
MSG: hexapodservice/legs\n\
hexapodservice/legjoints[6] leg\n\
";
  }

  static const char* value(const ::hexapodservice::hexapodserviceGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hexapodservice::hexapodserviceGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.MODE);
      stream.next(m.SIMPLEMOTION_MODE);
      stream.next(m.ONELEG);
      stream.next(m.ALLLEGS);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct hexapodserviceGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hexapodservice::hexapodserviceGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hexapodservice::hexapodserviceGoal_<ContainerAllocator>& v)
  {
    s << indent << "MODE: ";
    Printer<int32_t>::stream(s, indent + "  ", v.MODE);
    s << indent << "SIMPLEMOTION_MODE: ";
    Printer<int32_t>::stream(s, indent + "  ", v.SIMPLEMOTION_MODE);
    s << indent << "ONELEG: ";
    s << std::endl;
    Printer< ::hexapodservice::legjoints_<ContainerAllocator> >::stream(s, indent + "  ", v.ONELEG);
    s << indent << "ALLLEGS: ";
    s << std::endl;
    Printer< ::hexapodservice::legs_<ContainerAllocator> >::stream(s, indent + "  ", v.ALLLEGS);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HEXAPODSERVICE_MESSAGE_HEXAPODSERVICEGOAL_H
